### PR TITLE
TKO-44 -- FE: Create Edit Profile view and components

### PR DESCRIPTION
**Pull request by alecnicolas**
# Description
Created basic edit profile page.

Tried setting everything up with vuex, but am having a babel issue.
  
# Testing
Navigate to `/edit-profile`.

# Installation
yarn

### CODE REVIEW

**Review by andrewMETALAB — DISMISSED** [review]
I noticed that `editProfile.vue` is almost identical to `profileSetup.vue` - the only difference being:

(1) theres a "skip for now" link at the top of "profileSetup" that isnt at the top of "editProfile"
(2) "editProfile" will have saved data in each input while "profileSetup" will always have empty inputs

Can you please unify these 2 components into 1?

**Review by MikkalMc — CHANGES_REQUESTED** [review]
On reload, the page shows up as blank

**Comment by alecnicolas** [comment]
> On reload, the page shows up as blank

Wrong page

**Review by MikkalMc — APPROVED** [review]

**Review by raimahossain — APPROVED** [review]
Swooosh!

**Pull request merged**
